# Generated by Django 5.0.6 on 2024-07-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
