# Generated by Django 5.0.6 on 2024-07-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogApp', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myBlogApp.user'),
            preserve_default=False,
        ),
    ]
